=== things-library/Schemas/src/csharp/ThingsLibrary.Schema.Library/Schemas/1.0/item.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schema.thingslibrary.io/1.0/item.json",
  "$comment": "Items are the base data object of the things library. This schema is indentionally relaxed to allow maximum compatibility.  A item can contain key/value pairs of tags as well as other child items.",

  "$defs": {
    "item": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string",
          "title": "Key",
          "minLength": 1,
          "maxLength": 50
        },

        "date": {
          "type": "string",
          "title": "Date",
          "format": "date-time"
        },

        "name": {
          "type": "string",
          "title": "Name",
          "minLength": 1,
          "maxLength": 50
        },

        "type": {
          "type": "string",
          "title": "Type",
          "minLength": 1,
          "maxLength": 50
        },

        "tags": {
          "type": "object",
          "title": "Attribute Tags",
          "additionalProperties": {
            "anyOf": [
              {
                "title": "string",
                "type": "string"
              },
              {
                "title": "integer",
                "type": "integer"
              },
              {
                "title": "number",
                "type": "number"
              },
              {
                "title": "boolean",
                "type": "boolean"
              },
              {
                "title": "null",
                "type": "null"
              }
            ]
          }
        },

        "items": {
          "type": "object",
          "title": "Attachments",
          "additionalProperties": {
            "$ref": "#/$defs/item"
          }
        },

        "meta": {
          "type": "object",
          "title": "Metadata",
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "required": [ "type" ]
    }
  },

  "$ref": "#/$defs/item"
}

=== things-library/Schemas/docs/examples/service-canvas.json
{
    "$schema": "https://schema.thingslibrary.io/1.0/item.json",

    "type": "$canvas",
    "name": "Testing Services API",
    "tags": {
        "namespace": "TestServices.Api",
        "group": "Test Services",
        "environment": "Production",
        "host": "https://api.test.com"
    },

    "items": {
        "capabilities": {
            "type": "capabilities",
            "name": "Capabilities",
            "tags": {
                "healthChecks": "true",
                "openApi": "false",
                "controllers": "true",
                "httpRedirection": "true",
                "responseCompression": "true",
                "razorPages": "true",
                "serverSideBlazor": "false",
                "staticFiles": "true"
            }
        },
        "owner": {
            "type": "contact",
            "name": "Contact",
            "tags": {
                "name": "Tester McTesterson",
                "email": "test@test.com",
                "company": "Testing Group LLC"
            }
        },
        "authentication": {
            "type": "authentication",
            "name": "Authentication",
            "tags": {
                "login_url": "/account/login",
                "logout_url": "/account/logout",
                "access_denied_url": "/error/401"
            },
            "items": {  
                "azure_ad": {
                "type": "azure_ad",
                "name": "Azure AD Service",
                "tags": {
                    "authority": "https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/v2.0",
                    "domain": "testing.onmicrosoft.com",
                    "client_id": "00000000-0000-0000-0000-000000000000",                    
                    "scopes": "openid",                                          
                    "callback_path": "/signin-oidc"
                }
                },
                "jwt": {
                    "type": "jwt",
                    "name": "External JWT",
                    "tags": {                            
                        "authority": "https://signodeconnectusers.ciamlogin.com/00000000-0000-0000-0000-000000000000/v2.0",
                        "issuers": "https://sts.windows.net/00000000-0000-0000-0000-000000000000/|https://sts.windows.net/00000000-0000-0000-0000-000000000000/",
                        "audience": "00000003-0000-0000-c000-000000000000",                            
                        "name_claim_type": "name",
                        "role_claim_type": "roles",
                        "disable_validation": "true",
                        "show_validation_errors": "true"
                    }
                },
                "graph_api": {
                    "type": "ms_graph",
                    "name": "MS Graph API",
                    "tags": {
                        "tenant_id": "00000000-0000-0000-0000-000000000000",
                        "tenant_domain": "signodeconnectusers.onmicrosoft.com",
                        "client_id": "00000000-0000-0000-0000-000000000000",                        
                        "app_object_id": "00000000-0000-0000-0000-000000000000"
                    }
                }
            }
        },
        "authorization": {
            "type": "authorization",
            "name": "Authorization Policy",
            "items": {
                "roles": { 
                    "type": "roles",
                    "Name": "Application Roles",
                    "items": {
                        "testing.app": {
                            "type": "role",
                            "name": "Testing Services App",
                            "tags": {
                                "description": "Enables access to the Testing Services application"
                            },
                            "items": {
                                "00000000-0000-0000-0000-000000000000": {
                                    "type": "app_role",
                                    "name": "SC Testing Service"
                                },

                                "00000000-0000-0000-0000-000000000001": {
                                    "type": "security_group",
                                    "name": "PKG sg-Signode-All-d"
                                }
                            }
                        },
                        "impersonate": {
                            "type": "role",
                            "name": "Impersonate",
                            "tags": {
                                "description": "Enables an employee administrator to limit their current access so it matches what a specific user would see."
                            },
                            "items": {
                                "00000000-0000-0000-0000-000000000002": {
                                    "type": "app_role",
                                    "name": "Impersonate"
                                },
                                "00000000-0000-0000-0000-000000000003": {
                                    "type": "security_group",
                                    "name": "test-D365CE-PROD (dynamic)"
                                },
                                "00000000-0000-0000-0000-000000000004": {
                                    "type": "security_group",
                                    "name": "test-D365CE-PROD (manual)"
                                },

                                "00000000-0000-0000-0000-000000000005": {
                                    "type": "security_group",
                                    "name": "test-All-d"
                                }
                            }
                        }
                    }
                }
            }
        },
        "notifications": {
            "type": "notification",
            "name": "Notifications",
            "items": {
                "email": {
                    "type": "email",
                    "name": "Email Notifications",
                    "tags": {
                        "address_from": "DoNotReply@00000000-0000-0000-0000-000000000000.azurecomm.net",
                        "connection_string_variable": "Notifications"
                    }
                },
                "sms": {
                    "type": "sms",
                    "name": "SMS Notifications",
                    "tags": {
                        "address_from": "+18775555555",
                        "connection_string_variable": "Notifications"
                    }
                }
            }
        },
        "databases": {
            "type": "databases",
            "name": "Databases",
            "items": {
                "cosmos": {
                    "type": "database_cosmos",
                    "name": "Azure Cosmos DB",
                    "tags": {
                        "database_name": "connected-services",                            
                        "connection_string_variable": "EntityDatabase"
                    }
                },
                "fabric": {
                    "type": "database_fabric",
                    "name": "D365 CE Database",
                    "tags": {
                        "database_name": "",                            
                        "connection_string_variable": "ServiceDatabase"
                    }
                }
            }
        },
        "caching": {
            "type": "cache_cosmos",
            "name": "Azure Cache for REDIS",
            "tags": {                    
                "database_name": "connected-services",
                "container_name": "cache",                    
                "connection_string_variable": "EntityDatabase"
            }
        },
        "services": {
            "type": "services",
            "name": "Services",
            "items": {
                
            }
        }
    }
}
